[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stdresponse"
version = "0.1.0"
description = "A lightweight Python package for standardized API responses for Flask, FastAPI, and other servers."
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name="HARI KRISHNA", email="harikrishnabekkam1590852@gmail.com" }
]
keywords = ["flask", "fastapi", "api", "response", "standard_response"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = ["pydantic>=2.0"]

[project.urls]
Homepage = "https://github.com/HariKrishna070/standard_response.git"